version: '3'
services:
    mongodb:
        container_name: customer-stone
        image: mongo:latest
        restart: always
        ports:
            - 27022:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: customer
            MONGO_INITDB_ROOT_PASSWORD: customer
        volumes:
            - ./.docker/mongodb/entrypoints/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./.docker/mongodb/data:/data/db
