version: '3'
services:
    mongodb:
        container_name: ${API_NAME}-mongodb
        image: mongo:latest
        restart: always
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        volumes:
            - ./.docker/mongodb/entrypoints/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./.docker/mongodb/data:/data/db
        networks:
            - customer-dev-network
    redis:
        container_name: ${API_NAME}-redis
        image: redis:alpine
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
            - customer-dev-network
    api:
        container_name: ${API_NAME}
        build: .
        volumes:
            - .:/app
        ports:
            - ${API_PORT}:3000
        depends_on:
            - mongodb
            - redis
        networks:
            - customer-dev-network
networks:
    customer-dev-network:
